# Generated by Django 5.1.5 on 2025-01-19 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True, verbose_name='Immatriculation')),
                ('marque', models.CharField(max_length=255, verbose_name='Marque')),
                ('modele', models.CharField(max_length=255, verbose_name='Modèle')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('categorie', models.CharField(choices=[('Transporteur de marchandise', 'Transporteur de marchandise'), ('Ramasseur de déchet', 'Ramasseur de déchet'), ('Transporteur de passagers', 'Transporteur de passagers'), ('Autre', 'Autre')], max_length=255, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Indisponible', 'Indisponible')], default='Disponible', max_length=50, verbose_name='Statut')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('date_derniere_maintenance', models.DateField(blank=True, null=True, verbose_name='Date de dernière maintenance')),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name="URL de l'image")),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
