# Generated by Django 5.1.6 on 2025-02-15 23:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburant',
            name='cout_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix par litre en euros (ex: 520.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Coût unitaire'),
        ),
    ]
