# Generated by Django 5.1.5 on 2025-01-19 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculemanager', '0002_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prise', models.DateField(verbose_name='Date Prise')),
                ('quantite', models.FloatField(verbose_name='Quantité (L)')),
                ('cout_unitaire', models.FloatField(blank=True, null=True, verbose_name='Coût Unitaire')),
                ('cout_total', models.FloatField(blank=True, null=True, verbose_name='Coût Total')),
                ('type_carburant', models.CharField(max_length=50, verbose_name='Type Carburant')),
                ('station', models.CharField(max_length=255, verbose_name='Station')),
                ('kilometrage_actuel', models.PositiveIntegerField(verbose_name='Kilométrage Actuel')),
                ('vehicule_id', models.PositiveIntegerField(verbose_name='ID Véhicule')),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'Enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
            ],
            options={
                'verbose_name': 'Carburant',
                'verbose_name_plural': 'Carburants',
                'ordering': ['-date_prise'],
            },
        ),
    ]
