# Generated by Django 5.1.5 on 2025-01-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculemanager', '0003_carburant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carburant',
            name='vehicule_id',
        ),
        migrations.AddField(
            model_name='carburant',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculemanager.vehicule', verbose_name='Véhicule'),
        ),
    ]
