# Generated by Django 5.1.6 on 2025-02-16 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculemanager', '0004_remove_vehicule_image_url_vehicule_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField(verbose_name='Date de départ')),
                ('date_arrivee', models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('lieu_depart', models.CharField(max_length=255, verbose_name='Lieu de départ')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('depart_lat', models.FloatField(blank=True, null=True)),
                ('depart_lon', models.FloatField(blank=True, null=True)),
                ('destination_lat', models.FloatField(blank=True, null=True)),
                ('destination_lon', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('motif', models.TextField(verbose_name='Motif du trajet')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculemanager.vehicule')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'ordering': ['-date_depart'],
            },
        ),
    ]
