# Generated by Django 5.1.5 on 2025-01-19 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculemanager', '0004_remove_carburant_vehicule_id_carburant_vehicule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField(verbose_name='Date de départ')),
                ('date_arrivee', models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('lieu_depart', models.CharField(max_length=255, verbose_name='Lieu de départ')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('motif', models.TextField(blank=True, verbose_name='Motif du trajet')),
                ('status', models.CharField(default='En attente', max_length=50, verbose_name='Statut')),
                ('cout_estime', models.FloatField(blank=True, null=True, verbose_name='Coût estimé (€)')),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personnel')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculemanager.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'ordering': ['-date_depart'],
            },
        ),
    ]
